# Generated by Django 5.2.10 on 2026-01-27 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        ("users", "0001_initial"),
        ("wallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancealert",
            name="fiat_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Fiat transaction that triggered the alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_alerts",
                to="wallets.fiattransaction",
            ),
        ),
        migrations.AddField(
            model_name="compliancealert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compliancealert",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Crypto transaction that triggered the alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_alerts",
                to="wallets.transaction",
            ),
        ),
        migrations.AddField(
            model_name="compliancealert",
            name="user_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="compliance_alerts", to="users.useraccount"
            ),
        ),
        migrations.AddField(
            model_name="alertchecklistitem",
            name="alert",
            field=models.ForeignKey(
                help_text="The alert this checklist item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_items",
                to="compliance.compliancealert",
            ),
        ),
        migrations.AddField(
            model_name="customerriskassessment",
            name="assessed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_assessments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerriskassessment",
            name="user_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="risk_assessments", to="users.useraccount"
            ),
        ),
        migrations.AddField(
            model_name="compliancealert",
            name="monitoring_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Rule that triggered this alert (null for manual alerts)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_alerts",
                to="compliance.monitoringrule",
            ),
        ),
        migrations.AddField(
            model_name="transactionscreening",
            name="transaction",
            field=models.OneToOneField(
                help_text="Crypto transaction that was screened",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screening",
                to="wallets.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transactionscreening",
            name="user_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_screenings",
                to="users.useraccount",
            ),
        ),
        migrations.AddIndex(
            model_name="alertprocedurestep",
            index=models.Index(fields=["template", "order"], name="compliance__templat_0b198f_idx"),
        ),
        migrations.AddIndex(
            model_name="alertprocedurestep",
            index=models.Index(fields=["is_required"], name="compliance__is_requ_780ac9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="alertprocedurestep",
            unique_together={("template", "order")},
        ),
        migrations.AddIndex(
            model_name="alertchecklistitem",
            index=models.Index(fields=["alert", "is_completed"], name="compliance__alert_i_442a53_idx"),
        ),
        migrations.AddIndex(
            model_name="alertchecklistitem",
            index=models.Index(fields=["completed_by", "-completed_at"], name="compliance__complet_4f5d06_idx"),
        ),
        migrations.AddIndex(
            model_name="alertchecklistitem",
            index=models.Index(fields=["is_completed", "is_skipped"], name="compliance__is_comp_c617a3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="alertchecklistitem",
            unique_together={("alert", "step")},
        ),
        migrations.AddIndex(
            model_name="customerriskassessment",
            index=models.Index(fields=["user_account", "-created_at"], name="compliance__user_ac_af50b2_idx"),
        ),
        migrations.AddIndex(
            model_name="customerriskassessment",
            index=models.Index(fields=["assessment_status"], name="compliance__assessm_3c42b8_idx"),
        ),
        migrations.AddIndex(
            model_name="customerriskassessment",
            index=models.Index(fields=["overall_risk_rating"], name="compliance__overall_a9126d_idx"),
        ),
        migrations.AddIndex(
            model_name="compliancealert",
            index=models.Index(fields=["status", "-created_at"], name="compliance__status_894b2d_idx"),
        ),
        migrations.AddIndex(
            model_name="compliancealert",
            index=models.Index(fields=["user_account", "-created_at"], name="compliance__user_ac_37e6e0_idx"),
        ),
        migrations.AddIndex(
            model_name="compliancealert",
            index=models.Index(fields=["severity", "status"], name="compliance__severit_731a48_idx"),
        ),
        migrations.AddIndex(
            model_name="compliancealert",
            index=models.Index(fields=["triggered_rule"], name="compliance__trigger_de7ae5_idx"),
        ),
        migrations.AddIndex(
            model_name="compliancealert",
            index=models.Index(fields=["smr_required", "smr_filed_at"], name="compliance__smr_req_3b84c1_idx"),
        ),
        migrations.AddIndex(
            model_name="compliancealert",
            index=models.Index(fields=["account_action"], name="compliance__account_5b5912_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionscreening",
            index=models.Index(fields=["status"], name="compliance__status_dd0e8a_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionscreening",
            index=models.Index(fields=["to_address"], name="compliance__to_addr_4c3228_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionscreening",
            index=models.Index(fields=["risk_score"], name="compliance__risk_sc_5a9620_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionscreening",
            index=models.Index(fields=["user_account", "-created_at"], name="compliance__user_ac_ac022c_idx"),
        ),
    ]
