DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
LocalSocketMode 660
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
Foreground yes
LogTime yes
LogClean no
ExtendedDetectionInfo no
FailIfCvdOlderThan 7
ConcurrentDatabaseReload no
StreamMaxLength 10M
MaxFileSize 10M
MaxScanSize 64M
MaxRecursion 8
MaxFiles 1000
MaxScanTime 5000
MaxThreads 2
MaxQueue 8
ReadTimeout 10
CommandReadTimeout 5
AlertExceedsMax yes
AlertEncrypted yes
