# Generated by Django 5.2.17 on 2026-09-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_delete_authsession_refreshcredential"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserToken",
        ),
    ]
