# Generated by Django 5.2.10 on 2026-01-27 07:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, help_text="Trading symbol (e.g., BTC, ETH, USDC)", max_length=32, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full name (e.g., 'Bitcoin', 'Ethereum', 'USD Coin')", max_length=255),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("native_crypto", "Native Crypto"),
                            ("erc20_token", "Erc20 Token"),
                            ("stablecoin", "Stablecoin"),
                            ("tokenized_security", "Tokenized Security"),
                            ("tokenized_rwa", "Tokenized Rwa"),
                            ("synthetic", "Synthetic"),
                        ],
                        help_text="Type of asset",
                        max_length=32,
                    ),
                ),
                (
                    "chain",
                    models.CharField(
                        blank=True,
                        help_text="Blockchain chain (ethereum, bitcoin, polygon, etc.)",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "contract_address",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Smart contract address (if applicable)",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("decimals", models.IntegerField(default=18, help_text="Token decimals")),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=18, help_text="Latest price", max_digits=40, null=True
                    ),
                ),
                (
                    "price_currency",
                    models.CharField(default="USD", help_text="Currency for pricing (USD, EUR, etc.)", max_length=16),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this asset is actively tradable")),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["symbol"],
                "indexes": [
                    models.Index(fields=["symbol"], name="idx_asset_symbol"),
                    models.Index(fields=["asset_type"], name="idx_asset_type"),
                    models.Index(fields=["chain", "contract_address"], name="idx_asset_chain_contract"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetSnapshot",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=18, help_text="Price at snapshot time", max_digits=40)),
                ("price_currency", models.CharField(default="USD", help_text="Currency of price", max_length=16)),
                (
                    "market_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional market data (volume, market cap, etc.)"
                    ),
                ),
                ("source_timestamp", models.DateTimeField(help_text="When this data was captured")),
                (
                    "data_source",
                    models.CharField(
                        help_text="Source identifier (e.g., 'manual', 'provider_api', 'chainlink_oracle')",
                        max_length=64,
                    ),
                ),
                (
                    "block_number",
                    models.BigIntegerField(
                        blank=True, help_text="Blockchain block number (if from on-chain source)", null=True
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True, help_text="Transaction hash (if from on-chain source)", max_length=128, null=True
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset this snapshot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Snapshot",
                "verbose_name_plural": "Asset Snapshots",
                "db_table": "asset_snapshots",
                "ordering": ["-source_timestamp"],
                "indexes": [
                    models.Index(fields=["asset", "-source_timestamp"], name="idx_snap_asset_time"),
                    models.Index(fields=["source_timestamp"], name="idx_snap_time"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("asset", "source_timestamp"), name="unique_asset_snapshot")
                ],
            },
        ),
    ]
