# Generated by Django 5.2.17 on 2026-09-05 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0006_delete_fiattransaction_drop_unread_columns"),
        ("whitelist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelistentry",
            name="address",
            field=models.CharField(blank=True, help_text="Set only when the entry has no wallet.", max_length=42),
        ),
        migrations.AddField(
            model_name="whitelistentry",
            name="label",
            field=models.CharField(
                blank=True, help_text="Treasury or custodian name for a non-user address.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="whitelistentry",
            name="wallet",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whitelist_entry",
                to="wallets.wallet",
            ),
        ),
        migrations.AddConstraint(
            model_name="whitelistentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("wallet__isnull", False), models.Q(("address", ""), _negated=True), _connector="OR"
                ),
                name="whitelist_entry_wallet_or_address",
            ),
        ),
    ]
