# Generated by Django 6.0.3 on 2026-03-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("whitelist_add", "Add to Whitelist"),
                    ("whitelist_remove", "Remove from Whitelist"),
                    ("whitelist_update", "Update Investor Type"),
                    ("token_deploy", "Deploy Token"),
                    ("token_mint", "Mint Tokens"),
                    ("token_transfer", "Transfer Tokens"),
                    ("token_burn", "Burn Tokens"),
                    ("stablecoin_mint", "Mint Stablecoin"),
                    ("stablecoin_burn", "Burn Stablecoin"),
                    ("yield_token_mint", "Mint Yield Token"),
                    ("yield_token_nav_update", "Update Yield Token NAV"),
                    ("atomic_swap", "Atomic Swap"),
                    ("share_token_deploy", "Deploy Share Token"),
                    ("contract_deploy", "Deploy Contract"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
