WHITELIST_STATUS_WHITELISTED = "whitelisted"
WHITELIST_STATUS_NOT_WHITELISTED = "not_whitelisted"
WHITELIST_STATUS_UNKNOWN = "unknown"

WHITELIST_STATUS_CHOICES = [
    WHITELIST_STATUS_WHITELISTED,
    WHITELIST_STATUS_NOT_WHITELISTED,
    WHITELIST_STATUS_UNKNOWN,
]
