CURRENCY_AUD = "AUD"
CURRENCY_USD = "USD"
CURRENCY_EUR = "EUR"
CURRENCY_GBP = "GBP"
CURRENCY_CAD = "CAD"
CURRENCY_JPY = "JPY"
CURRENCY_NZD = "NZD"
CURRENCY_SGD = "SGD"

CURRENCY_LABEL_AUD = "Australian Dollar"
CURRENCY_LABEL_USD = "US Dollar"
CURRENCY_LABEL_EUR = "Euro"
CURRENCY_LABEL_GBP = "British Pound"
CURRENCY_LABEL_CAD = "Canadian Dollar"
CURRENCY_LABEL_JPY = "Japanese Yen"
CURRENCY_LABEL_NZD = "New Zealand Dollar"
CURRENCY_LABEL_SGD = "Singapore Dollar"

CURRENCY_CHOICES = [
    (CURRENCY_AUD, CURRENCY_LABEL_AUD),
    (CURRENCY_USD, CURRENCY_LABEL_USD),
    (CURRENCY_EUR, CURRENCY_LABEL_EUR),
    (CURRENCY_GBP, CURRENCY_LABEL_GBP),
    (CURRENCY_CAD, CURRENCY_LABEL_CAD),
    (CURRENCY_JPY, CURRENCY_LABEL_JPY),
    (CURRENCY_NZD, CURRENCY_LABEL_NZD),
    (CURRENCY_SGD, CURRENCY_LABEL_SGD),
]

CURRENCY_SYMBOLS = {
    CURRENCY_AUD: "A$",
    CURRENCY_USD: "$",
    CURRENCY_EUR: "€",
    CURRENCY_GBP: "£",
    CURRENCY_CAD: "C$",
    CURRENCY_JPY: "¥",
    CURRENCY_NZD: "NZ$",
    CURRENCY_SGD: "S$",
}

DEFAULT_CURRENCY = CURRENCY_AUD

DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"

BLOCKCHAIN_ETHEREUM = "ethereum"
BLOCKCHAIN_BITCOIN = "bitcoin"
BLOCKCHAIN_POLYGON = "polygon"
BLOCKCHAIN_SOLANA = "solana"
BLOCKCHAIN_AVALANCHE = "avalanche"
BLOCKCHAIN_ARBITRUM = "arbitrum"
BLOCKCHAIN_OPTIMISM = "optimism"
BLOCKCHAIN_BASE = "base"

VALID_BLOCKCHAINS = {
    BLOCKCHAIN_ETHEREUM,
    BLOCKCHAIN_BITCOIN,
    BLOCKCHAIN_POLYGON,
    BLOCKCHAIN_SOLANA,
    BLOCKCHAIN_AVALANCHE,
    BLOCKCHAIN_ARBITRUM,
    BLOCKCHAIN_OPTIMISM,
    BLOCKCHAIN_BASE,
}

EVM_BLOCKCHAINS = {
    BLOCKCHAIN_ETHEREUM,
    BLOCKCHAIN_POLYGON,
    BLOCKCHAIN_AVALANCHE,
    BLOCKCHAIN_ARBITRUM,
    BLOCKCHAIN_OPTIMISM,
    BLOCKCHAIN_BASE,
}

SUPPORTED_CHAINS = {
    BLOCKCHAIN_ETHEREUM,
    BLOCKCHAIN_BITCOIN,
    BLOCKCHAIN_BASE,
}

NATIVE_ASSET_TO_CHAIN = {
    "ETH": BLOCKCHAIN_ETHEREUM,
    "BTC": BLOCKCHAIN_BITCOIN,
    "POL": BLOCKCHAIN_POLYGON,
    "MATIC": BLOCKCHAIN_POLYGON,  # Legacy alias for POL
    "SOL": BLOCKCHAIN_SOLANA,
    "AVAX": BLOCKCHAIN_AVALANCHE,
}

CHAIN_TO_NATIVE_ASSET = {
    BLOCKCHAIN_ETHEREUM: "ETH",
    BLOCKCHAIN_BITCOIN: "BTC",
    BLOCKCHAIN_POLYGON: "POL",
    BLOCKCHAIN_SOLANA: "SOL",
    BLOCKCHAIN_AVALANCHE: "AVAX",
    BLOCKCHAIN_ARBITRUM: "ETH",
    BLOCKCHAIN_OPTIMISM: "ETH",
    BLOCKCHAIN_BASE: "ETH",
}


def normalize_chain(chain: str) -> str:
    if not chain:
        return ""
    normalized = chain.lower()
    if normalized in VALID_BLOCKCHAINS:
        return normalized
    upper = chain.upper()
    mapped = NATIVE_ASSET_TO_CHAIN.get(upper)
    if mapped:
        return mapped
    return normalized


def get_native_asset_symbol(chain: str) -> str:
    normalized = normalize_chain(chain)
    return CHAIN_TO_NATIVE_ASSET.get(normalized, normalized.upper())


JOB_STATUS_SCHEDULED = "scheduled"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"

JOB_STATUS_LABEL_SCHEDULED = "Scheduled"
JOB_STATUS_LABEL_RUNNING = "Running"
JOB_STATUS_LABEL_COMPLETED = "Completed"
JOB_STATUS_LABEL_FAILED = "Failed"

JOB_STATUS_CHOICES = [
    (JOB_STATUS_SCHEDULED, JOB_STATUS_LABEL_SCHEDULED),
    (JOB_STATUS_RUNNING, JOB_STATUS_LABEL_RUNNING),
    (JOB_STATUS_COMPLETED, JOB_STATUS_LABEL_COMPLETED),
    (JOB_STATUS_FAILED, JOB_STATUS_LABEL_FAILED),
]
