WALLET_VERIFICATION_STATUS_PENDING = "PENDING"
WALLET_VERIFICATION_STATUS_VERIFIED = "VERIFIED"

WALLET_VERIFICATION_STATUS_CHOICES = [
    (WALLET_VERIFICATION_STATUS_PENDING, "Pending Verification"),
    (WALLET_VERIFICATION_STATUS_VERIFIED, "Verified"),
]

TRANSACTION_STATUS_PENDING = "pending"
TRANSACTION_STATUS_CONFIRMED = "confirmed"
TRANSACTION_STATUS_FAILED = "failed"

TRANSACTION_STATUS_CHOICES = [
    (TRANSACTION_STATUS_PENDING, "Pending"),
    (TRANSACTION_STATUS_CONFIRMED, "Confirmed"),
    (TRANSACTION_STATUS_FAILED, "Failed"),
]

VERIFICATION_CHALLENGE_EXPIRY_MINUTES = 5

SNAPSHOT_REASON_BALANCE_SYNC = "BALANCE_SYNC"
SNAPSHOT_REASON_TRANSACTION = "TRANSACTION"
SNAPSHOT_REASON_DAILY = "DAILY"
SNAPSHOT_REASON_MANUAL = "MANUAL"
SNAPSHOT_REASON_RECONSTRUCTION = "RECONSTRUCTION"

SNAPSHOT_REASON_CHOICES = [
    (SNAPSHOT_REASON_BALANCE_SYNC, "Balance Sync"),
    (SNAPSHOT_REASON_TRANSACTION, "Transaction"),
    (SNAPSHOT_REASON_DAILY, "Daily"),
    (SNAPSHOT_REASON_MANUAL, "Manual"),
    (SNAPSHOT_REASON_RECONSTRUCTION, "Reconstruction"),
]
