WALLET_VERIFICATION_STATUS_PENDING = "PENDING"
WALLET_VERIFICATION_STATUS_VERIFIED = "VERIFIED"

WALLET_VERIFICATION_STATUS_CHOICES = [
    (WALLET_VERIFICATION_STATUS_PENDING, "Pending Verification"),
    (WALLET_VERIFICATION_STATUS_VERIFIED, "Verified"),
]

TRANSACTION_STATUS_PENDING = "pending"
TRANSACTION_STATUS_CONFIRMED = "confirmed"
TRANSACTION_STATUS_FAILED = "failed"
TRANSACTION_STATUS_REORGED = "reorged"
TRANSACTION_STATUS_REPLACED = "replaced"

TRANSACTION_STATUS_CHOICES = [
    (TRANSACTION_STATUS_PENDING, "Pending"),
    (TRANSACTION_STATUS_CONFIRMED, "Confirmed"),
    (TRANSACTION_STATUS_FAILED, "Failed"),
    (TRANSACTION_STATUS_REORGED, "Confirmed, then dropped by a chain reorganisation"),
    (TRANSACTION_STATUS_REPLACED, "Replaced by another transaction that landed instead"),
]

TRANSACTION_STATUSES_THAT_RETURN_THE_OPTIMISTIC_DEBIT = (
    TRANSACTION_STATUS_FAILED,
    TRANSACTION_STATUS_REORGED,
)

SNAPSHOT_REASON_TRANSACTION = "TRANSACTION"
SNAPSHOT_REASON_DAILY = "DAILY"

SNAPSHOT_REASON_CHOICES = [
    (SNAPSHOT_REASON_TRANSACTION, "Transaction"),
    (SNAPSHOT_REASON_DAILY, "Daily"),
]
