# Generated by Django 5.2.12 on 2026-04-07 07:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0007_stablecoin_reserve_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareIssuanceRequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_address", models.CharField(help_text="Ethereum address of the recipient", max_length=42)),
                (
                    "recipient_name",
                    models.CharField(blank=True, help_text="Name of the recipient (optional)", max_length=255),
                ),
                ("amount", models.PositiveIntegerField(help_text="Number of shares to issue")),
                (
                    "issuance_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Issuance"),
                            ("additional", "Additional Issuance"),
                            ("bonus", "Bonus Shares"),
                            ("dividend", "Dividend Reinvestment"),
                            ("transfer", "Transfer (Re-issuance)"),
                        ],
                        default="additional",
                        help_text="Type of issuance",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Purpose or justification for this issuance")),
                (
                    "dilution_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage dilution this issuance would cause to existing holders",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executing", "Executing"),
                            ("executed", "Executed"),
                            ("failed", "Failed"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, help_text="When the request was submitted", null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, help_text="When the request was reviewed", null=True)),
                ("review_notes", models.TextField(blank=True, help_text="Notes from the reviewer")),
                ("rejection_reason", models.TextField(blank=True, help_text="Reason for rejection (if rejected)")),
                (
                    "executed_at",
                    models.DateTimeField(blank=True, help_text="When the issuance was executed on-chain", null=True),
                ),
                (
                    "executed_issuance",
                    models.OneToOneField(
                        blank=True,
                        help_text="The executed ShareIssuance record for the minted shares",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issuance_request",
                        to="tokens.shareissuance",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who reviewed the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_issuance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_issuance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issuance_requests",
                        to="tokens.sharetoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Issuance Request",
                "verbose_name_plural": "Share Issuance Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token", "status"], name="tokens_shar_token_i_d88bfe_idx"),
                    models.Index(fields=["status"], name="tokens_shar_status_a2f450_idx"),
                ],
            },
        ),
    ]
