# Generated by Django 5.2.17 on 2026-09-03 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    """ShareIssuanceRequest joins the shared RequestStatus enum: its initial state is now 'submitted'."""
    ShareIssuanceRequest = apps.get_model("tokens", "ShareIssuanceRequest")
    ShareIssuanceRequest.objects.filter(status="pending_approval").update(status="submitted")


def backwards(apps, schema_editor):
    ShareIssuanceRequest = apps.get_model("tokens", "ShareIssuanceRequest")
    ShareIssuanceRequest.objects.filter(status="submitted").update(status="pending_approval")


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0011_transferorder_owner_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="capitalincreaserequest",
            name="dilution_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage dilution this request would cause to existing holders",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="capitalincreaserequest",
            name="executed_at",
            field=models.DateTimeField(blank=True, help_text="When the request was executed on-chain", null=True),
        ),
        migrations.AlterField(
            model_name="capitalincreaserequest",
            name="executed_issuance",
            field=models.OneToOneField(
                blank=True,
                help_text="The executed ShareIssuance record for the minted shares",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="tokens.shareissuance",
            ),
        ),
        migrations.AlterField(
            model_name="capitalincreaserequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who reviewed the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="capitalincreaserequest",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shareissuancerequest",
            name="dilution_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage dilution this request would cause to existing holders",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shareissuancerequest",
            name="executed_at",
            field=models.DateTimeField(blank=True, help_text="When the request was executed on-chain", null=True),
        ),
        migrations.AlterField(
            model_name="shareissuancerequest",
            name="executed_issuance",
            field=models.OneToOneField(
                blank=True,
                help_text="The executed ShareIssuance record for the minted shares",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="tokens.shareissuance",
            ),
        ),
        migrations.AlterField(
            model_name="shareissuancerequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who reviewed the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shareissuancerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("executing", "Executing"),
                    ("executed", "Executed"),
                    ("failed", "Failed"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shareissuancerequest",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
