# Generated by Django 5.2.17 on 2026-09-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0012_reviewable_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferorder",
            name="signature_request",
        ),
    ]
