# Generated by Django 5.2.8 on 2026-03-25 01:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import companies.models.document


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallets", "0004_wallet_is_operator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("trading_name", models.CharField(blank=True, max_length=255)),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("pty", "Proprietary Limited (Pty Ltd)"),
                            ("public", "Public Company (Ltd)"),
                            ("unlisted", "Unlisted Public Company"),
                        ],
                        default="pty",
                        max_length=20,
                    ),
                ),
                ("acn", models.CharField(max_length=11, unique=True)),
                ("abn", models.CharField(blank=True, max_length=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for Review"),
                            ("review", "Under Review"),
                            ("info_required", "Additional Information Required"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("warning", "Compliance Warning"),
                            ("suspended", "Suspended"),
                            ("delisted", "Delisted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postcode", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(blank=True, default="Australia", max_length=50)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("review_started_at", models.DateTimeField(blank=True, null=True)),
                ("review_completed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("info_requested_at", models.DateTimeField(blank=True, null=True)),
                ("info_request_reason", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("rejection_at", models.DateTimeField(blank=True, null=True)),
                ("warning_issued_at", models.DateTimeField(blank=True, null=True)),
                ("warning_reason", models.TextField(blank=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.TextField(blank=True)),
                ("delisted_at", models.DateTimeField(blank=True, null=True)),
                ("delisting_reason", models.TextField(blank=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=64, unique=True)),
                ("api_key_created_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator_wallet",
                    models.ForeignKey(
                        blank=True,
                        help_text="The wallet used for signing token operations",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operated_companies",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_company_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationReview",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("recused", "Recused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decision_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Internal review notes")),
                ("decision_reason", models.TextField(blank=True, help_text="Reason for approval/rejection")),
                ("review_order", models.PositiveSmallIntegerField(default=1)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="companies.company"
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Review",
                "verbose_name_plural": "Application Reviews",
                "ordering": ["company", "review_order"],
                "unique_together": {("company", "review_order"), ("company", "reviewer")},
            },
        ),
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("cert_inc", "Certificate of Incorporation"),
                            ("asic", "ASIC Company Extract"),
                            ("constitution", "Company Constitution"),
                            ("share_register", "Current Share Register"),
                            ("financials", "Financial Statements"),
                            ("auditor_report", "Auditor Report"),
                            ("director_id", "Director Identification"),
                            ("beneficial_ownership", "Beneficial Ownership Declaration"),
                            ("shareholder", "Shareholder Agreement"),
                            ("business_plan", "Business Plan"),
                            ("risk_disclosure", "Risk Disclosure Statement"),
                            ("prospectus", "Prospectus or Information Memorandum"),
                            ("legal_opinion", "Legal Opinion"),
                            ("tax_return", "Tax Return"),
                            ("bank_statement", "Bank Statement"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded file (preferred)",
                        null=True,
                        upload_to=companies.models.document.company_document_path,
                    ),
                ),
                ("external_url", models.URLField(blank=True, help_text="External URL if file is stored elsewhere")),
                ("file_size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="companies.company"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Document",
                "verbose_name_plural": "Company Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewNote",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "visible_to_company",
                    models.BooleanField(
                        default=False, help_text="If True, this note will be visible to the company representatives"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_notes_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_notes",
                        to="companies.applicationreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Note",
                "verbose_name_plural": "Review Notes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignatureRequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("token_deploy", "Deploy Token"),
                            ("share_issue", "Issue Shares"),
                            ("share_transfer", "Transfer Shares"),
                            ("token_pause", "Pause Token"),
                            ("token_unpause", "Unpause Token"),
                            ("whitelist_add", "Add to Whitelist"),
                            ("whitelist_remove", "Remove from Whitelist"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Signature"),
                            ("signed", "Signed"),
                            ("submitted", "Submitted to Blockchain"),
                            ("confirmed", "Confirmed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("transaction_data", models.JSONField()),
                ("message_to_sign", models.TextField(blank=True)),
                ("signature", models.TextField(blank=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("tx_hash", models.CharField(blank=True, max_length=66)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("error_message", models.TextField(blank=True)),
                (
                    "initiated_from",
                    models.CharField(
                        choices=[("admin", "Admin Panel"), ("portal", "Company Portal")],
                        default="portal",
                        max_length=20,
                    ),
                ),
                ("related_model", models.CharField(blank=True, max_length=100)),
                ("related_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_requests",
                        to="companies.company",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_signature_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signature_requests",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signature Request",
                "verbose_name_plural": "Signature Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="companies_s_status_38f606_idx"),
                    models.Index(fields=["request_type"], name="companies_s_request_3efa81_idx"),
                    models.Index(fields=["expires_at"], name="companies_s_expires_597701_idx"),
                ],
            },
        ),
    ]
