# Generated by Django 5.2.17 on 2026-09-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_delete_review_and_signature_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="additional_info_response",
            field=models.TextField(blank=True),
        ),
    ]
