# Generated by Django 5.2.10 on 2026-01-27 07:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("portfolios", "0001_initial"),
        ("shared", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(default="individual", max_length=20)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("joint", "Joint")], default="individual", max_length=20
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("activation_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "User Account",
                "verbose_name_plural": "User Accounts",
                "db_table": "customer_accounts_account",
            },
        ),
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the user signing up for the waitlist", max_length=254, unique=True
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the user subscribed to the waitlist"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether the waitlist subscription is active"),
                ),
            ],
            options={
                "verbose_name": "Waitlist Entry",
                "verbose_name_plural": "Waitlist Entries",
                "db_table": "accounts_waitlist",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor_type",
                    models.IntegerField(
                        choices=[(0, "None"), (1, "Retail"), (2, "Wholesale"), (3, "Institutional")], default=1
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone_country_code", models.CharField(blank=True, max_length=5, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=15, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("residential_address", models.TextField(blank=True, null=True)),
                ("id_document_type", models.CharField(blank=True, max_length=50, null=True)),
                ("id_document_country", models.CharField(blank=True, max_length=3, null=True)),
                ("confirmed_over_18", models.BooleanField(default=False)),
                ("confirmed_australian_resident", models.BooleanField(default=False)),
                ("confirmed_individual_account", models.BooleanField(default=False)),
                ("pre_screening_completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_id_verified", models.BooleanField(default=False)),
                ("terms_and_conditions", models.BooleanField(default=False)),
                ("is_signup_completed", models.BooleanField(default=False)),
                ("sumsub_applicant_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sumsub_verification_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("init", "Initialized"),
                            ("pending", "Pending Review"),
                            ("queued", "Queued for Review"),
                            ("completed", "Review Completed"),
                            ("onHold", "On Hold"),
                            ("prechecked", "Pre-checked"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sumsub_review_result",
                    models.CharField(
                        blank=True,
                        choices=[("GREEN", "Approved"), ("RED", "Rejected"), ("YELLOW", "Requires Attention")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sumsub_review_answer",
                    models.CharField(
                        blank=True,
                        choices=[("GREEN", "Accepted"), ("RED", "Rejected"), ("YELLOW", "Retry")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("sumsub_rejection_labels", models.JSONField(blank=True, null=True)),
                ("sumsub_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "citizenship_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citizens",
                        to="shared.country",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_onramp_provider",
                    models.CharField(
                        blank=True,
                        choices=[("transak", "Transak"), ("banxa", "Banxa")],
                        help_text="User's preferred fiat on-ramp provider for buying crypto",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "selected_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="User's selected account for quick access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_by_users",
                        to="users.useraccount",
                    ),
                ),
                (
                    "selected_portfolio",
                    models.ForeignKey(
                        blank=True,
                        help_text="User's selected portfolio for quick access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_by_users",
                        to="portfolios.portfolio",
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to="users.userprofile"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.AddField(
            model_name="useraccount",
            name="director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="directed_user_accounts",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="user_profiles",
            field=models.ManyToManyField(related_name="user_accounts", to="users.userprofile"),
        ),
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_alerts",
                    models.BooleanField(default=True, help_text="Notifications for transaction status changes"),
                ),
                (
                    "price_alerts",
                    models.BooleanField(default=False, help_text="Notifications for price threshold alerts"),
                ),
                ("marketing", models.BooleanField(default=False, help_text="Marketing and promotional notifications")),
                (
                    "user_profile",
                    models.OneToOneField(
                        help_text="User profile these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preferences",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "users_notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="FinancialProfile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        help_text="Customer's occupation for AML/CTF risk profiling",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "source_of_funds",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Primary source of funds: employment_income, savings, investment_income, sale_of_assets, inheritance, gift, other",
                        null=True,
                    ),
                ),
                (
                    "source_of_funds_other_text",
                    models.CharField(
                        blank=True,
                        help_text="Specification when 'other' is selected as source of funds",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "intended_use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("long_term_investment", "Long-term investment"),
                            ("trading_crypto", "Trading crypto currencies"),
                            ("savings", "Savings"),
                            ("other", "Other"),
                        ],
                        help_text="Customer's intended use of the platform",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "intended_use_other_text",
                    models.CharField(
                        blank=True,
                        help_text="Specification when 'other' is selected as intended use",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_profile",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Financial Profiles",
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "push_token",
                    models.CharField(
                        help_text="Expo push token (e.g., ExponentPushToken[xxx])", max_length=255, unique=True
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        help_text="Device platform (iOS or Android)",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this token is active and can receive notifications"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this token was used to send a notification"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Token",
                "verbose_name_plural": "Device Tokens",
                "db_table": "users_device_token",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="users_devic_user_id_aed98d_idx"),
                    models.Index(fields=["push_token"], name="users_devic_push_to_8d60f9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FavouriteAsset",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="The asset that is marked as favourite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_assets",
                        to="assets.asset",
                    ),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        help_text="The user account that owns this favourite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_assets",
                        to="users.useraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favourite Asset",
                "verbose_name_plural": "Favourite Assets",
                "db_table": "favourite_assets",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_account", "asset"), name="unique_favourite_asset_per_user_account"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (primary key)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("HOLDINGS", "Holdings"),
                            ("WALLETS", "Wallets"),
                            ("TRANSACTIONS", "Transactions"),
                            ("TRANSFER", "Transfer"),
                            ("PORTFOLIO", "Portfolio"),
                            ("ASSETS", "Assets"),
                        ],
                        default="HOLDINGS",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="widgets", to="users.useraccount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget",
                "verbose_name_plural": "Widgets",
                "db_table": "widgets",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("user_account", "name"), name="unique_widget_per_user_account")
                ],
            },
        ),
    ]
