# Generated by Django 5.2.17 on 2026-09-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_add_display_currency_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="kycaid_verification_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="pre_screening_completed_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="sumsub_rejection_labels",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="sumsub_review_answer",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="sumsub_review_result",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="sumsub_verified_at",
        ),
    ]
