# Generated by Django 5.2.17 on 2026-09-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    # compliance/0005 drops ComplianceAlert.fiat_transaction, the last FK into fiat_transactions.
    dependencies = [
        ("compliance", "0005_remove_fiat_transaction_and_high_risk_country"),
        ("wallets", "0005_alter_holdingsnapshot_snapshot_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holding",
            name="last_synced_block",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="custody_model",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="is_operator",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="is_whitelisted_for_securities",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="last_synced_block",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="reconstruction_complete",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="reconstruction_completed_at",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="reconstruction_status",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="whitelisted_at",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="whitelisting_authority",
        ),
        migrations.DeleteModel(
            name="FiatTransaction",
        ),
    ]
