# Generated by Django 5.2.17 on 2026-09-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0003_remove_portfolio_template_and_target_asset_allocation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssetAllocation",
        ),
    ]
