# Generated by Django 5.2.17 on 2026-09-05 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0004_delete_assetallocation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PortfolioSnapshot",
        ),
    ]
